tasks:
  - init: echo "Replace me with a build script for the project."
    command: echo "Replace me with something that should run on every start, or just
      remove me entirely."
vscode:
  extensions:
    - MS-CEINTL.vscode-language-pack-zh-hans@1.450:9Xum7Tc2l393C65cKlhhqA==
    - actboy168.lua-debug@1.23.4:K+eDo8iRV75G7ng+Qsq8eQ==
image:
  file: .gitpod.Dockerfile
